# Generated by Django 4.2.3 on 2023-08-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.TextField(default=0, verbose_name='url'),
        ),
    ]
