# Generated by Django 4.2.3 on 2023-08-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_entry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.TextField(default=0),
        ),
    ]
