# Generated by Django 4.1.7 on 2023-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_alter_entry_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.TextField(),
        ),
    ]
