# Generated by Django 4.1.7 on 2023-08-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_alter_entry_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='url',
        ),
    ]
