# Generated by Django 4.1.7 on 2023-08-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0005_remove_entry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
